### ISSUE TITLE
Transport is not connected, write directive to 'Secure Connection' ignored.

### ISSUE THREAD

**Issue by mwelkers** [nonolk/domoticz_tahoma_blind#10]
I quite often get this error which (after extensive Google-ing) suggests that the polling frequency is to high to the Connexoon so that the connection freezes. Is there a way to reduce the polling frequency? Can that be done by increasing the heartbeat value and heartbeat delay value?

**Comment by nonolk** [comment]
Hello,

To be honest I get this error rarely not more than once a month (even less), it just because at a certain time Domoticz was unable to connect to the Tahoma api, and it could come from several reasons, like internet provider peering issues.....

To answer your question for the moment it's not possible to change de heartbeat value, except by editing the code, maybe in a future version.

Best regards,
