### ISSUE TITLE
Error in Domoticz Logfiles. 

### ISSUE THREAD

**Issue by Gerard-Oedzes** [nonolk/domoticz_tahoma_blind#17]
Plugin is still working great! but i got lots of errors in the logfiles: 

`2020-12-14 14:24:09.715 Error: (Somfy Tahoma): Async Secure Read Exception: 336151548, sslv3 alert bad record mac`

**Comment by nonolk** [comment]
Hello,
As stated on the [homepage,](https://github.com/nonolk/domoticz_tahoma_blind#issues) this is not an issue, at least not one I can solve, it’s due to either a bad configuration of one of the somfy servers, or a corrupted packet. The plugin is not managing anything on ssl certificate.

**Comment by nono031** [comment]
Just a comment, I can't use the plugin due to this error. It appears every 30s to few minutes and after a couple of hours, Domoticz takes stuck and I have to restart the service using a SSH connection... My hardware setup contains also a Netatmo plugin and a dummy (handling ESP8266 HTTP request)
Thanks for your work !

**Comment by nonolk** [comment]
Hello, I’m really doubting it comes from this error, I had it several time per day without any issue on domoticz. As explained this just ssl handshake error, and it’s totally outside of my control, all the connection stuff is managed directly by domoticz itself. If you want to help you must provide useful information like: debug logs, domoticz and python version etc. And one more thing, do not answer on a closed issue.
