### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by vspamn** [nonolk/domoticz_tahoma_blind#7]
I keep getting the following error:

`Tahoma auth error`

I verified my credentials through https://dev.duboc.pro/tools/setup (server: TaHoma / Connexoon). I am using a Connexoon.

Any ideas?

**Comment by nonolk** [comment]
Hello,

This basically means there is an issue with your email address and/or password.... and nothing else. 

Maybe check your email address and be careful to the case, as for some reason the Connexoon/Tahoma api is case sensitive on the email address. 

Otherwise I have no idea and as your are the only one having this issue, I suspect something on your side. Sorry

Best regards,

**Comment by vspamn** [comment]
Thanks nonolk. Your comment made me change my password and downgrade it (<30 characters and no specials), which resulted in a working plugin. Could this be a bug in your plugin or at Somfy's end?

**Comment by nonolk** [comment]
Hello again,

I don’t think it’s coming from somfy. I suspect something with domoticz password field, as I’m doing nothing on the password variable expect providing it to the Tahoma api.

I also do have specials characters in my password including @. So maybe something due to the length of your password and domoticz field....

Otherwise honestly I have no idea.

Sorry,
